# Log level
logging:
  level:
    root: INFO
    com.huytmb: DEBUG
    org.springframework.integration: DEBUG

# Mail
mail:
  pop3:
    ssl: true
    host: pop.163.com
    port: 995
    username: jtrminsk%40163.com
    password: AFEZWLDCHEVZXDIZ
#  imap:
#    ssl: true
#    host: imap.qiye.aliyun.com
#    port: 993
#    username: jtrkiev%40aliyun.com
#    password: JFK181235

# Task execution
spring:
  task:
    execution:
      thread-name-prefix: autohost-task-
      pool:
        core-size: 2
        max-size: 200
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: mail-receiver-
      pool:
        size: 2